<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title></title>
</head>
<body>
  https://zh.javascript.info/promise-error-handling

  <script>

    const fetchSth = async () => {
      const [res1, res2] = await Promise.all([getPa(), getPb()]);
      console.log('fetch something')
    };
    const login = () => new Promise((resolve, reject) => {
      req.post('/url').then((res) => {
        resolve();
      }).catch((e) => {
        console.log(e);
        reject();
      });
    });
    useEffect(() => {
      setState({ loading: true });
      login().then(fetchSth).then(() => setState({ loading: false }));
    }, []);


    var getA = cb => cb('a');
    var getB = cb => cb('b');
    var getC = cb => cb('c');
    // callback
    getA(a => {
      console.log(a);
      getB(b => {
        console.log(b);
        getC(c => {
          console.log(c);
        })
      })
    })

    // promise
    var getPa = () => new Promise((resolve, reject) => setTimeout(() => resolve('pa'), 500));
    var getPb = () => new Promise((resolve, reject) => setTimeout(() => resolve('pb'), 500));
    var getPc = () => new Promise((resolve, reject) => setTimeout(() => resolve('pc'), 500));
    getPa().then(a => {
      console.log(a);
      return getPb(a)
    }).then(b => {
      console.log(b);
      return getPc(b)
    }).then(c => {
      console.log(c);
    });


    function timeout(duration = 0) {
      return new Promise((resolve, reject) => {
        setTimeout(resolve, duration);
      });
    }
    timeout(1000).then(() => {
      return 1;
    }).then(arg => {
      console.log(arg);
      return 'sth';
    }, err => {
      console.log('catch', err)
    }).then(arg => {
      console.log(arg);
      throw new Error("hmm");
    }).catch(err => {
      console.log('final catch', err)
    });


    Promise.all([
      new Promise(function (resolve, reject) {
        console.log('reject 先执行，后边 promise 内容是否会执行了？');
        window.addEventListener('DOMContentLoaded', () => resolve('dom ready'));
        // window.addEventListener('DOMContentLoaded', () => reject('dom ready'));
        // return reject('reject immediately');
      }),
      new Promise(function (resolve) {
        window.addEventListener('DOMContentLoaded', () => resolve('dom ready'));
        // return reject('reject again');
      }),
      new Promise(function (resolve) {
        console.log('p1');
        window.addEventListener('DOMContentLoaded', () => resolve('dom ready'));
      }),
      new Promise(function (resolve) {
        console.log('fake promise');
        resolve('fake promise');
      })
    ]).then(res => console.log('res: ', res), rej => console.log(rej));

    // 不管成功失败，都返回所有结果，不退出
    Promise.almost = r => Promise.all(r.map(p => p.catch ? p.catch(e => e) : p));
  </script>
</body>
</html>
